/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2021-10-15 00:43:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MemberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입 MAKING</title>\r\n");
      out.write("<script src = \"./JS/juminCheck.js\" charset = \"UTF-8\"></script>\r\n");
      out.write("<script src = \"./JS/chagne_email.js\" charset = \"UTF-8\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.title {\r\n");
      out.write("\t\tmargin : 40px 30px 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.container{\r\n");
      out.write("\t\twidth : 900px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.right {\r\n");
      out.write("\t\tfloat : right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.red{\r\n");
      out.write("\t\tcolor : red;\r\n");
      out.write("\t}\r\n");
      out.write("\ttbody.tbody > tr{\r\n");
      out.write("\t\tdisplay : table, width : 900px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttbody.tbody>tr>td:nth-child(1){\r\n");
      out.write("\t\twidth : 16%;\r\n");
      out.write("\t\tvertical-align : middle;\r\n");
      out.write("\t\tdisplay : table-cell;\r\n");
      out.write("\t\ttext-align : center;\r\n");
      out.write("\t}\r\n");
      out.write("\ttbody.tbody>tr>td:nth-child(2){\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#detailAddress::placeholder{\r\n");
      out.write("\t\tcolor:blue;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type = \"button\" value = \"Testing\" onclick = \"testing()\"/>\r\n");
      out.write("\t<form name = \"memberForm\" method = \"POST\" action = \"Member_control.jsp\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<input type = \"hidden\" name = \"action\" value = \"insert\" />\r\n");
      out.write("\t\t<div align = \"center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<h1 class = \"title\">회원가입</h1>\r\n");
      out.write("\t\t\t<div class = \"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class = \"right\">\r\n");
      out.write("\t\t\t\t\t<span class = \"red\">*</span>필수입력사항\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<table border = \"2\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan = \"2\" border = \"0\" bgcolor = \"orange\">회원 기본 정보</th>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tbody class = \"tbody\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>아이디<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"mem_id\" placeholder = \"6자 이상의 영문자와 숫자\" required autofocus/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"button\" value = \"ID중복확인\" onclick = \"idCheck(mem_id.value);\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>비밀번호<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"password\" name = \"mem_passwd\" maxlength = \"12\" minlength = \"8\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>8~12자리의 영문 대문자와 숫자, 특수문자만 입력</span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>이름<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"mem_name\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>닉네임<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"mem_nickname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmaxlength = \"12\" minlength = \"2\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>2~8자리의 한글로만 입력</span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>이메일<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"mem_email_id\" id = \"email_id\"/>@\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"mem_email_domain\" id = \"email_add\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name = \"email_sel\" id = \"email_sel\" style = \"font-size:16px; height : 30px;\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonchange = \"change_email()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"nate.com\">nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"kakao.com\">kakao.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"korea.com\">korea.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value = \"dreamwiz.com\">dreamwiz.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>주민번호<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"mem_num1\" maxlength = \"6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonkeyup = \"if(this.value.length==6)memberForm.mem_num2.focus();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"text\" name = \"mem_num2\" maxlength = \"7\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick = \"juminCheck(mem_num1.value, mem_num2.value)\">ss</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"button\" value = \"주민번호 정상 유무 체크\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick = \"juminCheck(mem_num1.value, mem_num2.value)\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>핸드폰번호<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"tel\" name = \"mem_phone\" pattern = \"(010)-[0-9]{4}-[0-9]{4}\" required/>\r\n");
      out.write("\t\t\t\t\t\t\t\t(예)010-1234-5678\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>성별</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"radio\" name = \"new_gender\" value = \"남성\" checked />남성&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"radio\" name = \"mem_gender\" value = \"여성\"/>여성\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>생년월일<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar today = new Date();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar toyear = parseInt(today.getFullYear());  //2021를 얻어옴!\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar start = toyear - 15;   //네이버인 경우 만14세 이상 회원가입 가능!\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar end = toyear - 80;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"<select name = mem_Birthday1>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor ( i = start ; i >= end ; i --){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write(\"<option value = '\"+i+\"'>\"+i);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"</select>년 \");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"<select name = mem_Birthday2>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor ( i = 2 ; i <= 12 ; i ++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write(\"<option value = '\"+i+\"'>\"+i);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"</select>월 \");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"<select name = mem_Birthday3>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor ( i = 2 ; i <= 31 ; i ++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.write(\"<option value = '\"+i+\"'>\"+i);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.write(\"</select>일 \");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>주소<span class = \"red\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class = \"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type = \"text\" name = \"zipCode\" id = \"postcode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder = \"우편번호\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type = \"button\" onclick = \"execDaumPostcode()\" value = \"우편번호 찾기\"  />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type = \"text\" name = \"userAddr1\" id = \"address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsize = \"100\" placeholder = \"주소\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type = \"text\" name = \"userAddr3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid = \"extraAddress\" size = \"48\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder = \"참고항목( 도로명인 경우: 지역이름과 아파트)\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type = \"text\" name = \"userAddr2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid = \"detailAddress\" size = \"45\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder = \"상세주소(아파트 동호수 또는 빌딩이름 입력하세요!)\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"layer\" style=\"display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\" id=\"btnCloseLayer\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"closeDaumPostcode()\" alt=\"닫기 버튼\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    // 우편번호 찾기 화면을 넣을 element\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    var element_layer = document.getElementById('layer');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    function closeDaumPostcode() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        element_layer.style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    function execDaumPostcode() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        new daum.Postcode({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            oncomplete: function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                var addr = ''; // 주소 변수\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    addr = data.roadAddress;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    addr = data.jibunAddress;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                if(data.userSelectedType === 'R'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                        extraAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    if(extraAddr !== ''){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    document.getElementById(\"extraAddress\").value = extraAddr;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t\t\t\t\t\t                } else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                    document.getElementById(\"extraAddress\").value = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                document.getElementById('postcode').value = data.zonecode;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                document.getElementById(\"address\").value = addr;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                document.getElementById(\"detailAddress\").focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t                element_layer.style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            width : '100%',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            height : '100%',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t            maxSuggestItems : 5\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        }).embed(element_layer);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        // iframe을 넣은 element를 보이게 한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        element_layer.style.display = 'block';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        initLayerPosition();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    // 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    // resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    // 직접 element_layer의 top,left값을 수정해 주시면 됩니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    function initLayerPosition(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        var width = 300; //우편번호서비스가 들어갈 element의 width\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        var height = 400; //우편번호서비스가 들어갈 element의 height\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        var borderWidth = 5; //샘플에서 사용하는 border의 두께\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        // 위에서 선언한 값들을 실제 element에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        element_layer.style.width = width + 'px';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        element_layer.style.height = height + 'px';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        element_layer.style.border = borderWidth + 'px solid';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        // 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width)/2 - borderWidth) + 'px';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height)/2 - borderWidth) + 'px';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan = \"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"submit\" value = \"회원가입 등록\"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type = \"reset\" valye = \"다시쓰기\" />\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
